### PR TITLE
wfd: Don't assert on strange videoformat input

### LINKED ISSUE #76: LG TV sends  wfd_video_formats that breaks MaskToEnumList()
@pozdnyakov , you maybe have an idea about this...

(desktop-source-test:13925): rtsp-DEBUG: Sending RTSP message:
OPTIONS * RTSP/1.0
CSeq: 1
Require: org.wfa.wfd1.0

* scan complete
(desktop-source-test:13925): rtsp-DEBUG: Received RTSP message:
RTSP/1.0 200 OK
CSeq: 1
Public: org.wfa.wfd1.0, GET_PARAMETER, SET_PARAMETER

OPTIONS * RTSP/1.0
CSeq: 1
User-Agent: LGE
Require: org.wfa.wfd1.0

(desktop-source-test:13925): rtsp-DEBUG: Sending RTSP message:
RTSP/1.0 200 OK
CSeq: 1
Public: org.wfa.wfd1.0, GET_PARAMETER, SET_PARAMETER, PLAY, PAUSE, SETUP, TEARDOWN

(desktop-source-test:13925): rtsp-DEBUG: Sending RTSP message:
GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
CSeq: 2
Content-Length: 59

wfd_video_formats
wfd_audio_codecs
wfd_client_rtp_ports

(desktop-source-test:13925): rtsp-DEBUG: Received RTSP message:
RTSP/1.0 200 OK
CSeq: 2
Content-Type: text/parameters
Content-Length: 276

wfd_audio_codecs: LPCM 00000003 00, AAC 00000007 00, AC3 00000007 00
wfd_video_formats: 40 00 01 08 0001FFFF 3FFFFFFF 000005FF 00 0000 0000 10 none none, 02 08 0001FFFF 3FFFFFFF 000005FF 00 0000 0000 10 none none
wfd_client_rtp_ports: RTP/AVP/UDP;unicast 19000 0 mode=play

desktop-source-test: /home/wysiwidi/src/wysiwidi/wfd/parser/videoformats.cpp:131: std::vector<EnumType> wfd::{anonymous}::MaskToEnumList(ArgType, EnumType) [with EnumType = wfd::VESARatesAndResolutions; ArgType = unsigned int]: Assertion `false' failed.
Aborted

### PR DESCRIPTION
**Pull request by jku**
Skip reserved supportmask values, don't assert.

Fixes #76.

Should note that the MaskToEnum() function is still broken and would assert on same input.

@kanavin If you're fixing the codec handling, you'll probably end up rewriting these functions: so feel free to disregard if this clashes with your changes. I wanted to fix this since it makes the desktop_source work with last of our test sinks -- at least with some streaming quality.

### CODE REVIEW

**Comment by kanavin** [comment]
Sure. Generally, asserts should be used to catch our mistakes, not 3rd parties'.

"Be generous in what you accept, rigorous in what you emit".

I'm going to fix the video format hadling by splitting H264VideoFormat into SupportedH264VideoFormat (a set of resolutions) and SelectedH264VideoFormat (just one resolution like now). And add a new constructor to H264Codec so that either can be supplied to create a H264Codec. Then fix up the rest of the code.

File: wfd/parser/videoformats.cpp [hunk 1]
```diff
@@ -127,10 +127,9 @@ std::vector<EnumType> MaskToEnumList(ArgType from, EnumType biggest_value) {
 
   while (copy != 0) {
     if ((copy & 1) != 0) {
-      if (enum_value > static_cast<unsigned>(biggest_value)) {
-        assert(false);
+      if (enum_value > static_cast<unsigned>(biggest_value))
         break;
-      }
```
Comment (pozdnyakov) [inline wfd/parser/videoformats.cpp]: there should be error logging, or at least comment that this is something unexpectable

**Comment by pozdnyakov** [comment]
lgtm

File: wfd/parser/videoformats.cpp (hunk 1 above)
Comment (jku) [inline wfd/parser/videoformats.cpp]: I would have added debug logging but we don't seem to have any support for that in wfd. I thought GLib logging (that @alexshalamov used in mirac_network) was a fine idea ... but it doesn't really make sense in wfd that doesn't depend on GLib: we can't add that dependency for just logging. I guess I should add a macro that depends on CMAKE_BUILD_TYPE...

Comment (pozdnyakov) [inline wfd/parser/videoformats.cpp]: We can add logging later, after #84 is merged
